---
- name: Azure VM provisioning
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    deploymentID: "{{ deploymentID }}"
    location: "{{ location }}"
    azure_client_id: "{{ lookup('ansible.builtin.env', 'AZURE_CLIENT_ID') }}"
    azure_secret: "{{ lookup('ansible.builtin.env', 'AZURE_SECRET') }}"
    azure_tenant: "{{ lookup('ansible.builtin.env', 'AZURE_TENANT') }}"
    azure_subscription_id: "{{ lookup('ansible.builtin.env', 'AZURE_SUBSCRIPTION_ID') }}"

  tasks:
    - name: Obtain Azure REST API Access Token
      ansible.builtin.uri:
        url: "https://microsoftonline.com/{{ azure_tenant }}/oauth2/v2.0/token"
        method: POST
        body_format: form-urlencoded
        body:
          client_id: "{{ azure_client_id }}"
          grant_type: client_credentials
          scope: "https://azure.com"
          client_secret: "{{ azure_secret }}"
        status_code: 200
      register: token_response

    - name: Create resource group
      ansible.builtin.uri:
        url: "https://azure.com/{{ azure_subscription_id }}/resourcegroups/{{ resource_group }}?api-version=2021-04-01"
        method: PUT
        status_code: [200, 201]
        headers:
          Authorization: "Bearer {{ token_response.json.access_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          location: "{{ location }}"
          tags:
            deploymentID: "{{ deploymentID }}"

    - name: Create virtual network and subnet
      ansible.builtin.uri:
        url: "https://azure.com/{{ azure_subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Network/virtualNetworks/{{ network_name }}?api-version=2023-11-01"
        method: PUT
        status_code: [200, 201]
        headers:
          Authorization: "Bearer {{ token_response.json.access_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          location: "{{ location }}"
          tags:
            deploymentID: "{{ deploymentID }}"
          properties:
            addressSpace:
              addressPrefixes:
                - "{{ network_cidr }}"
            subnets:
              - name: "{{ subnet_name }}"
                properties:
                  addressPrefix: "{{ subnet_cidr }}"

    - name: Create Network Security Group
      ansible.builtin.uri:
        url: "https://azure.com/{{ azure_subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Network/networkSecurityGroups/{{ security_group }}?api-version=2023-11-01"
        method: PUT
        status_code: [200, 201]
        headers:
          Authorization: "Bearer {{ token_response.json.access_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          location: "{{ location }}"
          tags:
            deploymentID: "{{ deploymentID }}"
          properties:
            securityRules:
              - name: allow_web_traffic
                properties:
                  protocol: Tcp
                  destinationPortRange: "{{ tcp_ports }}"
                  access: Allow
                  priority: 1002
                  direction: Inbound
                  sourceAddressPrefix: '*'
                  sourcePortRange: '*'
                  destinationAddressPrefix: '*'

    - name: Create network interface
      ansible.builtin.uri:
        url: "https://azure.com/{{ azure_subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Network/networkInterfaces/{{ nic_name }}?api-version=2023-11-01"
        method: PUT
        status_code: [200, 201]
        headers:
          Authorization: "Bearer {{ token_response.json.access_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          location: "{{ location }}"
          tags:
            deploymentID: "{{ deploymentID }}"
          properties:
            ipConfigurations:
              - name: default
                properties:
                  privateIPAllocationMethod: Dynamic
                  subnet:
                    id: "/subscriptions/{{ azure_subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Network/virtualNetworks/{{ network_name }}/subnets/{{ subnet_name }}"
                  networkSecurityGroup:
                    id: "/subscriptions/{{ azure_subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Network/networkSecurityGroups/{{ security_group }}"

    - name: Create VM with Managed Disk
      ansible.builtin.uri:
        url: "https://azure.com/{{ azure_subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Compute/virtualMachines/{{ vm_name }}?api-version=2023-09-01"
        method: PUT
        status_code: [200, 201]
        headers:
          Authorization: "Bearer {{ token_response.json.access_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          location: "{{ location }}"
          tags:
            deploymentID: "{{ deploymentID }}"
          properties:
            hardwareProfile:
              vmSize: Standard_DS1_v2
            storageProfile:
              imageReference:
                publisher: "{{ publisher }}"
                offer: "{{ offer }}"
                sku: "{{ sku }}"
                version: latest
              osDisk:
                name: "{{ vm_name }}_os_disk"
                createOption: FromImage
                managedDisk:
                  storageAccountType: Standard_LRS
            osProfile:
              computerName: "{{ vm_name }}"
              adminUsername: "{{ username }}"
              adminPassword: "{{ password }}"
            networkProfile:
              networkInterfaces:
                - id: "/subscriptions/{{ azure_subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Network/networkInterfaces/{{ nic_name }}"
