---
- name: Azure VM provisioning
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    deploymentID: "{{ deploymentID }}"
    location: "{{ location }}"
    azure_client_id: "{{ lookup('ansible.builtin.env', 'AZURE_CLIENT_ID') }}"
    azure_secret: "{{ lookup('ansible.builtin.env', 'AZURE_SECRET') }}"
    azure_tenant: "{{ lookup('ansible.builtin.env', 'AZURE_TENANT') }}"
    azure_subscription_id: "{{ lookup('ansible.builtin.env', 'AZURE_SUBSCRIPTION_ID') }}"

  tasks:
    - name: Obtain Azure REST API Access Token
      ansible.builtin.uri:
        url: "https://microsoftonline.com/{{ azure_tenant }}/oauth2/v2.0/token"
        method: POST
        body_format: form-urlencoded
        body:
          client_id: "{{ azure_client_id }}"
          grant_type: client_credentials
          scope: "https://azure.com"
          client_secret: "{{ azure_secret }}"
        status_code: 200
      register: token_response

    - name: Create resource group via Native REST API
      ansible.builtin.uri:
        url: "https://azure.com/{{ azure_subscription_id }}/resourcegroups/{{ resource_group }}?api-version=2021-04-01"
        method: PUT
        status_code: 200, 201
        headers:
          Authorization: "Bearer {{ token_response.json.access_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          location: "{{ location }}"
          tags:
            deploymentID: "{{ deploymentID }}"

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "{{ network_name }}"
        address_prefixes:
          - "{{ network_cidr }}"
        tags:
          deploymentID: "{{ deploymentID }}"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: "{{ subnet_name }}"
        address_prefix: "{{ subnet_cidr }}"
        virtual_network: "{{ network_name }}"

    - name: Create Network Security Group
      azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: "{{ security_group }}"
        rules:
          - name: allow_web_traffic
            protocol: Tcp
            destination_port_range: "{{ tcp_ports }}"
            access: Allow
            priority: 1002
            direction: Inbound
        tags:
          deploymentID: "{{ deploymentID }}"

    - name: Create network interface
      azure_rm_networkinterface:
        name: "{{ nic_name }}"
        resource_group: "{{ resource_group }}"
        virtual_network: "{{ network_name }}"
        subnet_name: "{{ subnet_name }}"
        security_group: "{{ security_group }}"
        ip_configurations:
          - name: default
            primary: true
        tags:
          deploymentID: "{{ deploymentID }}"

    - name: Create VM with Managed Disk
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        vm_size: Standard_DS1_v2
        admin_username: "{{ username }}"
        admin_password: "{{ password }}"
        network_interface_names:
          - "{{ nic_name }}"
        os_type: "{{ os_type }}"
        image:
          offer: "{{ offer }}"
          publisher: "{{ publisher }}"
          sku: "{{ sku }}"
          version: latest
        managed_disk_type: Standard_LRS
        tags:
          deploymentID: "{{ deploymentID }}"
      register: vm

    - name: Debug VM output
      debug:
        var: vm
