---
- name: Secure Azure VM provisioning via Direct REST API
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    azure_client_id: "{{ lookup('ansible.builtin.env', 'AZURE_CLIENT_ID') }}"
    azure_secret: "{{ lookup('ansible.builtin.env', 'AZURE_SECRET') }}"
    azure_tenant: "{{ lookup('ansible.builtin.env', 'AZURE_TENANT') }}"
    azure_subscription_id: "{{ lookup('ansible.builtin.env', 'AZURE_SUBSCRIPTION_ID') }}"
    public_ip_name: "pip-{{ vm_name }}"

  tasks:

    - name: Obtain Azure REST API Access Token
      ansible.builtin.uri:
        url: "https://login.microsoftonline.com/{{ azure_tenant }}/oauth2/v2.0/token"
        method: POST
        body_format: form-urlencoded
        body:
          client_id: "{{ azure_client_id }}"
          client_secret: "{{ azure_secret }}"
          grant_type: client_credentials
          scope: "https://management.azure.com/.default"
        status_code: 200
      register: token_response

    - debug:
        msg: "Authenticated to Azure."

    - name: Create Resource Group
      ansible.builtin.uri:
        url: "https://management.azure.com/subscriptions/{{ azure_subscription_id }}/resourceGroups/{{ resource_group }}?api-version=2021-04-01"
        method: PUT
        headers:
          Authorization: "Bearer {{ token_response.json.access_token }}"
          Content-Type: application/json
        body_format: json
        body:
          location: "{{ location }}"
          tags:
            deploymentID: "{{ deploymentID }}"
        status_code: [200,201]
      register: rg_output

    - name: Create VNet
      ansible.builtin.uri:
        url: "https://management.azure.com/subscriptions/{{ azure_subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Network/virtualNetworks/{{ network_name }}?api-version=2023-11-01"
        method: PUT
        headers:
          Authorization: "Bearer {{ token_response.json.access_token }}"
          Content-Type: application/json
        body_format: json
        body:
          location: "{{ location }}"
          tags:
            deploymentID: "{{ deploymentID }}"
          properties:
            addressSpace:
              addressPrefixes:
                - "{{ network_cidr }}"
            subnets:
              - name: "{{ subnet_name }}"
                properties:
                  addressPrefix: "{{ subnet_cidr }}"
        status_code: [200,201]
      register: vnet_output

    - name: Create NSG
      ansible.builtin.uri:
        url: "https://management.azure.com/subscriptions/{{ azure_subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Network/networkSecurityGroups/{{ security_group }}?api-version=2023-11-01"
        method: PUT
        headers:
          Authorization: "Bearer {{ token_response.json.access_token }}"
          Content-Type: application/json
        body_format: json
        body:
          location: "{{ location }}"
          tags:
            deploymentID: "{{ deploymentID }}"
          properties:
            securityRules:
              - name: allow_web_traffic
                properties:
                  protocol: Tcp
                  sourcePortRange: "*"
                  destinationPortRanges: "{{ tcp_ports | from_json }}"
                  sourceAddressPrefix: "*"
                  destinationAddressPrefix: "*"
                  access: Allow
                  priority: 1002
                  direction: Inbound
        status_code: [200,201]
      register: nsg_output

    - name: Create Public IP
      ansible.builtin.uri:
        url: "https://management.azure.com/subscriptions/{{ azure_subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Network/publicIPAddresses/{{ public_ip_name }}?api-version=2023-11-01"
        method: PUT
        headers:
          Authorization: "Bearer {{ token_response.json.access_token }}"
          Content-Type: application/json
        body_format: json
        body:
          location: "{{ location }}"
          sku:
            name: Standard
          properties:
            publicIPAllocationMethod: Static
        status_code: [200,201]
      register: pip_output

    - name: Create NIC
      ansible.builtin.uri:
        url: "https://management.azure.com/subscriptions/{{ azure_subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Network/networkInterfaces/{{ nic_name }}?api-version=2023-11-01"
        method: PUT
        headers:
          Authorization: "Bearer {{ token_response.json.access_token }}"
          Content-Type: application/json
        body_format: json
        body:
          location: "{{ location }}"
          properties:
            networkSecurityGroup:
              id: "/subscriptions/{{ azure_subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Network/networkSecurityGroups/{{ security_group }}"
            ipConfigurations:
              - name: ipconfig1
                properties:
                  privateIPAllocationMethod: Dynamic
                  subnet:
                    id: "/subscriptions/{{ azure_subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Network/virtualNetworks/{{ network_name }}/subnets/{{ subnet_name }}"
                  publicIPAddress:
                    id: "/subscriptions/{{ azure_subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Network/publicIPAddresses/{{ public_ip_name }}"
        status_code: [200,201]
      register: nic_output

    - name: Create VM
      ansible.builtin.uri:
        url: "https://management.azure.com/subscriptions/{{ azure_subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Compute/virtualMachines/{{ vm_name }}?api-version=2023-09-01"
        method: PUT
        headers:
          Authorization: "Bearer {{ token_response.json.access_token }}"
          Content-Type: application/json
        body_format: json
        body:
          location: "{{ location }}"
          tags:
            deploymentID: "{{ deploymentID }}"
          properties:
            hardwareProfile:
              vmSize: Standard_DS1_v2
            storageProfile:
              imageReference:
                publisher: "{{ publisher }}"
                offer: "{{ offer }}"
                sku: "{{ sku }}"
                version: latest
              osDisk:
                createOption: FromImage
                managedDisk:
                  storageAccountType: Standard_LRS
            osProfile:
              computerName: "{{ vm_name }}"
              adminUsername: "{{ username }}"
              adminPassword: "{{ password }}"
              linuxConfiguration:
                disablePasswordAuthentication: false
            networkProfile:
              networkInterfaces:
                - id: "/subscriptions/{{ azure_subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Network/networkInterfaces/{{ nic_name }}"
                  properties:
                    primary: true
        status_code: [200,201,202]
      register: vm_output

    - debug:
        var: vm_output.status
